# Generated by Django 3.2.12 on 2022-04-19 21:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('implementation', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Savings_Plan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('owners_name', models.CharField(max_length=50)),
                ('transaction_fees', models.FloatField()),
                ('administration_fees', models.FloatField()),
                ('TER', models.FloatField()),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='implementation.investmentaccount')),
                ('deposit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='implementation.investmentdeposit')),
            ],
        ),
        migrations.DeleteModel(
            name='Portfolio',
        ),
    ]
